### PR TITLE
Changing the build system to CMake

### PR DESCRIPTION
**Pull request by 0bhat**
Right now  the plugin only works on *nix.
On windows the plugin is building but doesn't show up in the Pidgin.

Windows support is underway.

### CODE REVIEW

**Comment by EionRobb** [comment]
That's a shame to lose the commit history of the original plugin. Is it not possible to import all the original commits from the hg repo to keep the history?

**Comment by dequis** [comment]
As I mentioned in #516, the branch called "libpurple-integration" (i didn't pick the name) has that

**Comment by 0bhat** [comment]
It's going to to very complicated to do that, and I don't know `hg` too well either.
Let's make a new start by paying homage to the original authors everywhere in the code.

**Comment by EionRobb** [comment]
I appreciate the work you've done here, but losing the history is a deal-breaker.  Keeping the history of changes (to understand the "why") is pretty important for a protocol plugin to understand what makes it tick and what changes can be made without breaking things.

If you want to rebase against the libpurple-integration branch and attach the CMake scripts to that then we can review that PR, but right now this PR is solving nothing

**Comment by 0bhat** [comment]
That's ok, I'm going to continue my work on my fork then.

**Pull request closed without merging**
