### PR TITLE
Bump the FB_ORCA_AGENT version

### PR DESCRIPTION
**Pull request by mrc0mmand**
Based on bitlbee/bitlbee-facebook#208

Fixes: #498

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Tested the build at least locally (`./autogen.sh && make`) and it seems to build as expected. The original version in the patch is a bit different than what's in the pidgin/pidgin trunk, since `patches/14-the-future.patch` bumps it as well.

**Comment by dequis** [comment]
Thanks!

**Comment by MikeTango** [comment]
hex edited libfacebook.so, works for me.

**Comment by alexolog** [comment]
A Windows DLL will be appreciated

**Pull request merged**
