### PR TITLE
Fix taNewMessage bug

### PR DESCRIPTION
**Pull request by baltitenger**
based on [nuxi's PR on bitblee-facebook](https://github.com/bitlbee/bitlbee-facebook/pull/202)

### CODE REVIEW

**Comment by nuxi** [comment]
Only the 1st and 2nd hunks of that diff are based on my PR. The 3rd and 4th hunks of that are based on https://github.com/bitlbee/bitlbee-facebook/pull/199 which was fixing a different issue.

**Comment by EionRobb** [comment]
In a perfect world that change would make its way into the pidgin3 code, but in a more perfect world all of the plugin code would be extracted out of pidgin3 and into this plugin 👍

**Comment by alexolog** [comment]
Can we please get a Windows DLL with the fix?
Thank you!

**Comment by EionRobb** [comment]
@alexolog https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows supposedly picks up the builds from https://travis-ci.org/github/dequis/purple-facebook/builds/737558791

**Comment by dequis** [comment]
It failed, just like the bitlbee-facebook one did. It just doesn't show up as a failure because it's in the `after_success` step

**Comment by nuxi** [comment]
osc appears to be python3 now and python3-m2crypto is only available in Ubuntu 20.04 (focal) and newer.

**Comment by IcyInsanities** [comment]
Hi,

Just to know, is that issue something feasible to fix or is there another way to get a windows dll? (I realize this is volunteer maintained, and I do really appreciate the time spent to maintain over the years, so just seeing if it's time to adjust to a new workflow here.)

Thanks!

**Pull request merged**
